spring:
  datasource:
    url: ${DATABASE_URL:jdbc:h2:file:./data/real-estate-finder}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}
  h2:
    console:
      enabled: false

logging:
  level:
    root: WARN
